server:
  port: 8081
spring:
  application:
    name: test1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
test2: # 调用test2服务时，使用RandomRule规则
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      default: #default是指对所有服务生效
        loggerLevel: FULL #日志级别
  #      test2: #只对test2生效
  #        loggerLevel: FULL #日志级别
  httpclient:
    enabled: true