server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes: #网关路由配置
        - id: test-three #路由id，自定义 只要唯一即可
        #  uri: http://127.0.0.1:8889 # 路由的目标地址，http是固定地址
          uri: lb://test3 # 路由的目标地址 lb是指负载均衡 后面跟服务名称
          predicates: #路由断言 判断路由是否符合路由规则
            - Path=/test3/** # 只要以test3开头就符合规则
          filters:
            - AddRequestHeader=name, xiefei # 所有访问test3的请求加一个请求头
        - id: test-two
          uri: lb://test2
          predicates:
            - Path=/test2/**
      default-filters:
        - AddRequestHeader=all, allAdd # 所有的路由加一个请求头
      globalcors:
        add-to-simple-url-handler-mapping: true # 允许options的询问请求
        cors-configurations:
          '[/**]': #拦截哪些请求，/**是拦截一切请求，凡是经过网关的请求，都做跨域处理
            allowedOrigins: #允许哪些网站跨域
              - "http://localhost:6666"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedGeaders: "*" # 允许请求中携带的头信息
            allowedCredentials: true # 是否允许带cookie
            maxAge: 360000 # 这次跨域检测的有效期