server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        cluster-name: JS #集群名称，江苏  负载均衡默认是轮询，不区分集群
        #namespace: 111 #命名空间id，用来做环境隔离
        ephemeral: false # false表示不是临时实例，临时实例挂了注册中心不会保留，不是临时实例的话，注册中心会保留
  rabbitmq:
    host: 47.100.60.104
    port: 5672
    username: admin
    password: admin
    virtual-host: /itcast

test4: # 调用test4服务时，使用NacosRule规则,优先本地集群，然后随机选择服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    #如果该服务访问其他服务也会有限访问江苏的集群内的服务
