server:
  port: 8085
spring:
  application:
    name: test3
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: JS #集群名称，江苏  负载均衡默认是轮询，不区分集群

test4: # 调用test4服务时，使用NacosRule规则,优先本地集群，然后随机选择服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    #如果该服务访问其他服务也会有限访问江苏的集群内的服务
